// Code generated by MockGen. DO NOT EDIT.
// Source: channel_inputport.go

// Package mock_inputport is a generated GoMock package.
package mock_inputport

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/shima004/chat-server/entities"
	validation "github.com/shima004/chat-server/usecases/inputport/validation"
)

// MockChannelUsecase is a mock of ChannelUsecase interface.
type MockChannelUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockChannelUsecaseMockRecorder
}

// MockChannelUsecaseMockRecorder is the mock recorder for MockChannelUsecase.
type MockChannelUsecaseMockRecorder struct {
	mock *MockChannelUsecase
}

// NewMockChannelUsecase creates a new mock instance.
func NewMockChannelUsecase(ctrl *gomock.Controller) *MockChannelUsecase {
	mock := &MockChannelUsecase{ctrl: ctrl}
	mock.recorder = &MockChannelUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelUsecase) EXPECT() *MockChannelUsecaseMockRecorder {
	return m.recorder
}

// CreateChannel mocks base method.
func (m *MockChannelUsecase) CreateChannel(ctx context.Context, in *validation.CreateChannelInput) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChannel", ctx, in)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChannel indicates an expected call of CreateChannel.
func (mr *MockChannelUsecaseMockRecorder) CreateChannel(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChannel", reflect.TypeOf((*MockChannelUsecase)(nil).CreateChannel), ctx, in)
}

// DeleteChannel mocks base method.
func (m *MockChannelUsecase) DeleteChannel(ctx context.Context, in *validation.DeleteChannelInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChannel", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChannel indicates an expected call of DeleteChannel.
func (mr *MockChannelUsecaseMockRecorder) DeleteChannel(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChannel", reflect.TypeOf((*MockChannelUsecase)(nil).DeleteChannel), ctx, in)
}

// FetchChannel mocks base method.
func (m *MockChannelUsecase) FetchChannel(ctx context.Context, in *validation.FetchChannelInput) (*entities.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchChannel", ctx, in)
	ret0, _ := ret[0].(*entities.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchChannel indicates an expected call of FetchChannel.
func (mr *MockChannelUsecaseMockRecorder) FetchChannel(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchChannel", reflect.TypeOf((*MockChannelUsecase)(nil).FetchChannel), ctx, in)
}
