version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./../../SlackClone:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
