name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"
          cache: true
          cache-dependency-path: go/go.sum

      - name: Go lint
        uses: golangci/golangci-lint-action@v3

      - name: Setup Go Packages
        run: go install github.com/golang/mock/mockgen@latest

      - name: Generate Mocks
        run: |
          rm -rf mock
          go generate ./...
        working-directory: ./go

      - name: Go Build
        run: go build -v ./...
        working-directory: ./go

      - name: Go Test
        run: go test -v ./...
        working-directory: ./go
